apiVersion: v1
entries:
  ceph-csi-drivers:
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2026-04-16T11:46:07.900559182+02:00"
    description: A Helm chart for Ceph CSI drivers
    digest: c1c2495691cecbf62e391a6801024f706cdaddc4d73e6ff47f5ed5693fabbed6
    name: ceph-csi-drivers
    type: application
    urls:
    - https://scaedufax.github.io/ceph-csi-operator/charts/ceph-csi-drivers-0.6.0+legacy.tgz
    version: 0.6.0+legacy
  ceph-csi-operator:
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2026-04-16T11:46:07.909699827+02:00"
    description: A Helm chart to distribute the project ceph-csi-operator
    digest: 39dfc20608d9ad56c83f16d0199b7264d606aed89e4ccc314883e57bfc9bd7c5
    name: ceph-csi-operator
    type: application
    urls:
    - https://scaedufax.github.io/ceph-csi-operator/charts/ceph-csi-operator-0.6.0+legacy.tgz
    version: 0.6.0+legacy
generated: "2026-04-16T11:46:07.89767545+02:00"
